name: task_manager
description: Advanced Task Manager App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  flutter_slidable: ^3.0.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  googleapis: ^14.0.0
  url_launcher: ^6.3.1
  googleapis_auth: ^2.0.0
  table_calendar: ^3.0.9
  fl_chart: ^1.0.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  timezone: ^0.10.1
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700